### ISSUE TITLE
Redesign Goals

### ISSUE THREAD

**Issue by EdwardBock** [palasthotel/grid#429]
## UI

 - [ ] High Contrast for Presenations and old Monitors
 - [ ] Better represenations for new Boxes in Sidebar ( #411 Julia Reusable Boxes)
 - [ ] Structure format Box Settings placed on Grid? ( #411 Kim )
 - [ ] Prevent loss of Focus on Edit Modes (Container- and Boxeditor #411 Kim)
 - [ ] uniformed loading indicators
 - [ ] Death to Sidebars? (Toolbar, Boxes, Containers all to top #411 kim )

## UX

 - [ ] Remeber collapsed state of Sidebar (New Container and Boxes)
 - [ ] Remeber collapsed state of Boxeditor and Container Editor
 - [ ] Loading indicators where to the place where loading is happening
